### ISSUE TITLE
MacOSx initialization error 

### ISSUE THREAD

**Issue by lindanlee** [blbradley/zcash-swing-wallet-ui#14]
Hello, 

I'm Linda, an employee of Zcash that uses OSx.

When I download the wallet, it throws a critical error as soon as I try to initialize the wallet. I didn't take a look at the logfile. Could you fix this? 

![image](https://user-images.githubusercontent.com/6580269/43095146-7c8557ea-8e7a-11e8-8490-4431ff2b5c6c.png)

We're really excited for a sapling-ready full node GUI wallet that builds on multiple platforms. Feel free to reach out if you need any assistance.

**Comment by blbradley** [comment]
I haven't experienced this on macOS. So, I'd need your logfile.

**Comment by blbradley** [comment]
What version of macOS are you on? I've only been able to test on High Sierra (the latest macOS release).

**Comment by lindanlee** [comment]
Oops, I was on an old version, I think: 

![image](https://user-images.githubusercontent.com/6580269/43151815-6bf102ea-8f32-11e8-8703-278814efa676.png)

Where is the logfile, by the way? I couldn't find it. A directory path would help. I'll try updating the computer and hope that resolves things. I had a colleague who couldn't get the wallet to work on his computer either--I'll ask what version he is on.

**Comment by lindanlee** [comment]
![image](https://user-images.githubusercontent.com/6580269/43152290-d0e3f06c-8f33-11e8-86d9-e7bd55e5737e.png)

I'm running an older OS version. 

Could you tell me the path to the logfile? I can't seem to find it. In the meantime, I'll install the OS upgrade on my mac and see if that works.

**Comment by blbradley** [comment]
Hey Linda!

* `~/Library/Application Support/Zcash/debug.log` for the ZCash server log.
* `~/Library/Application Support/ZCashSwingWalletUI/ZCashGUIWallet_2018_7_debug.log` for the UI log.

ZenCash swing wallet, the software which this wallet is based on, explicitly dropped support for El Capitan. So, I don't think I support it either.

Let me know if upgrading your OS fixes your issue. Happy to help! And thanks for reporting.

Cheers!
Brandon

**Comment by lindanlee** [comment]
Brandon, I don't see the debug log: 

![image](https://user-images.githubusercontent.com/6580269/43152715-e711a068-8f34-11e8-8d3d-6853f0ee9792.png)

I'm still downloading the upgrade.

**Comment by blbradley** [comment]
Can you try using Finder from your home directory?

In case you don't know, `~` is shorthand in the terminal for your home directory.

Your full paths should be

* `/Users/Lindas-MBP/Library/Application\ Support/Zcash/debug.log`
* `/Users/Lindas-MBP/Library/Application\ Support/ZCashSwingWalletUI/ZCashGUIWallet_2018_7_debug.log`

**Comment by lindanlee** [comment]
I installed the upgrade, and the wallet works now. 

Thanks for the clarification; for what it's worth: 

For /Users/Lindas-MBP/Library/Application\ Support/Zcash/debug.log: 
![image](https://user-images.githubusercontent.com/6580269/43155311-ad9cfc9e-8f3c-11e8-8070-b6f39413c948.png)
 
For /Users/Lindas-MBP/Library/Application\ Support/ZCashSwingWalletUI/ZCashGUIWallet_2018_7_debug.log (not the full log, but the rest is just full of [INFO] lines): 
![image](https://user-images.githubusercontent.com/6580269/43155415-f85b0ee2-8f3c-11e8-8ef7-7ec7e4860338.png)

**Comment by blbradley** [comment]
No problem, Linda! I'm happy people are testing the wallet, feel free to file any other issues you find.
